### ISSUE TITLE
cannot open the "overall" zip file

### ISSUE THREAD

**Issue by Anthony-Sun-S** [Evanwu1125/ChartInsights#1]
is there any thing wrong with the file in Dataset/Overall Evaluation/Charts/Overall.zip ? it shows this is an empty file, so I cannot unzip it.

**Comment by Anthony-Sun-S** [comment]
same as Dataset/Visual Prompt/Charts/Visual Prompt.zip

**Comment by ChartInsight** [comment]
Sorry about this problem, we will upload new zips as soon as possible.

**Comment by Evanwu1125** [comment]
We have upload the Visual Prompt and Overall images in GoogleDrive. Here is 
 the link: https://drive.google.com/drive/folders/1Yvn0v1txqWTe2R9nPaP7PTZPMiztJp0u?usp=sharing
